### ISSUE TITLE
Change how LogPipe is passed so all Loader log messages are available

### ISSUE THREAD

**Issue by rotateLeft** [kevoreilly/CAPEv2#116]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

All Loader log messages should be shown in CAPE Analysis log.

# Current Behavior

Calls to DoOutputDebugString and DoOutputErrorString in Loader only function after ReadConfig has been called, since that's where the random-named LogPipe is defined. This only happens for "injection" and "load" executions.

## Steps to Reproduce

Review Analysis log and notice many DoOutputDebugString and DoOutputErrorString calls are absent, such as "DoOutputDebugString("CAPE loader.\n");"

Maybe the LogPipe can be passed as an argument to Loader invocation???

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 9046ad63a3564ecb3225f4062767ca51dc12b347 (HEAD -> capemon, origin/capemon, origin/HEAD)
| OS version       | Ubuntu 18.04.4 LTS

**Comment by rotateLeft** [comment]
Sorry, I realise this should be in CapeMon repo :(

**Comment by kevoreilly** [comment]
Hi rotateLeft! Thanks a lot for the feedback. It's actually intentional that these log messages don't make it into the analysis log of the sandbox. We wouldn't want "CAPE loader" appearing every time the loader is called!

The real reason they're in there is because the loader is intended as dual-use. The CAPE monitor can be run in standalone mode by supplying a config.ini with standalone=1 inside. It can therefore be used for manual reverse engineering, or this can also be a convenient way to do monitor dev.

If you check the DoOutputDebugString function you will see it calls both pipe and OutputDebugString. Its dual use is thus that it also sends these messages to the system debug log, and thus they can be viewed by using Sysinternals DebugView.

Here's an example screenshot debugging a recent QakBot sample locally using the loader and monitor in standalone mode where you can see the log messages that are intended for local use but not logged in the sandbox:

![image](https://user-images.githubusercontent.com/22219888/78284483-6a84b100-7517-11ea-93e7-1f9f6b619875.png)
