### ISSUE TITLE
Results not displayed

### ISSUE THREAD

**Issue by bartblaze** [kevoreilly/CAPEv2#141]
Sample that has some anti-dbg functionality for older debugger such as SoftIce etc., opens handles to

- \??\NTICE
- \??\SICE
- \??\SIWDEBUG

Sig:
https://github.com/kevoreilly/community/blob/0c517f27af3ceefa7c1fbb8d4f79e80aba6fdc9e/modules/signatures/antidbg_devices.py

Issue: 
Hits are not displayed. For example:

> Checks for the presence of known devices from debuggers and forensic tools
If you click on the results, it displays blank, it should display the found results.

Example:
https://capesandbox.com/analysis/15081/

**Comment by doomedraven** [comment]
ya, that is bcz 
```
for indicator in indicators:
            if self.check_file(pattern=indicator, regex=True):
                return True

        return False
```

it not adding data to show, so that is correct behavior :P is easy to show what it matches, but not file, for get file match you need to rewrite the whole sig

i have pushed update that will show you how to implement that feature and you can add that where it missed ;) 

https://github.com/kevoreilly/community/commit/544ae8fef86acfc751e23c4163d2bf4e84d9b18f
