### ISSUE TITLE
password option not used in excel 2013 with xls package

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#161]
Example: https://capesandbox.com/analysis/288/

**Comment by doomedraven** [comment]
thanks, just tested, looks like sflock doesn't handle it

**Comment by doomedraven** [comment]
i just tested https://github.com/herumi/msoffice and it also doesn't support that, so we can't do nothing with this

**Comment by seanthegeek** [comment]
Hmm. Even if we can't decrypt the static file, could we at least have cuckoomon input the password and click ok, so at least get the runtime data?

**Comment by doomedraven** [comment]
cuckoomon is dead, long live capemon ;P 
but no that would be a problem there was an issue about this in one of the repos i think in cuckoo-modified, MS doesn't provide iface for easy manipulation, but \cc @kevoreilly  maybe he can do some magic

**Comment by doomedraven** [comment]
what can solve this is interactive mode, which @enzok  started to port, but I don't have time to handle everything by myself, so if someone can help with that would be cool

**Comment by seanthegeek** [comment]
Is that purely a Python 2 to 3 port.? I could do that. I know nothing about writing win32 C++ for capemon :P

**Comment by doomedraven** [comment]
yes + cape adaptation, check if enzok still has a branch for that, not sure, maybe he can tell us more

**Comment by enzok** [comment]
I lost the branch I was working on to incorporate guacamole into CAPE. I was able to recover some of the work, but didn't have the energy to recreate all of it. At the time I was focusing on VSphere interaction which ultimately was proving to be impractical due to recent VSphere changes. It should be much more possible to get something working with KVM though.
