### ISSUE TITLE
Sflock 2 causes cape-web to crash

### ISSUE THREAD

**Issue by kenleejl** [kevoreilly/CAPEv2#1631]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior

Allow Sflock2 to recognise that it is a jpeg file?

# Current Behavior

What is the current behavior?

Cape web just crashes when submitting a JFIF or JPEG file

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Just any random JPEG or JFIF file
2. Submit with Detect Automatically from Analysis Package
3. The whole cape-web crashes

Tested on capesandbox.com can be used as DOS

**Comment by doomedraven** [comment]
thanks, just got report in PM about that, working on it

**Comment by doomedraven** [comment]
that looks like is due to unicorn problem with that fileformat, i have added handle and reject it, but some other fileformats can generate the same, in case if you don't care about shellcode detections just change in database.py check_shellcode to False and it won't run unicorn for any file
`tmp_package = sflock_identify(f, check_shellcode=False)` 

to fix that just upgrade `sflock2` to latest version 0.3.51
