### ISSUE TITLE
Office "auto_close" not triggered

### ISSUE THREAD

**Issue by reynas** [kevoreilly/CAPEv2#169]
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Macros executed by auto_close, should be triggered somehow
OR
Make it possible to access the VM via the browser

# Current Behavior

auto_close macros are listed in the static analysis, but nothing shows in the behavioral analysis because the file doesn't close while running the analysis.

## Steps to Reproduce

1. Upload a office document with auto_close macro
2. analyse with entering the VM
3. Upload an office document with auto_close macro
4. During the analysis, enter the vm and close the document
5. Compare results (specifically the behavioral analysis)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| Git commit       |  fab86b48ac1307954b84d95d2543e3999d8b9c32
| OS version       |Host: Ubuntu 18.04, client:Windows 7

**Comment by doomedraven** [comment]
We have a lot of other priorities rigth now, so you are welcome to
colaborate and implement that

**Comment by kevoreilly** [comment]
The tricky part is 4: during analysis, enter vm and close document! Easier said than done :-)

The existing technology in cape for automating the interaction inside the vm is the human auxiliary module. I believe it's quite limited in terms of which gui components it can "see" in order to be able to click on, but this would be the place to start.

Let me know how you get on, I look forward to the pull request :-)
