### ISSUE TITLE
No report being generated

### ISSUE THREAD

**Issue by grimjr90** [kevoreilly/CAPEv2#1724]
Hello,

I'm having a lot of trouble installing CAPEv2 Sandbox into my VMWare, tried so many times almost over 15+ times and I finally managed to get it to work however I'm facing an issue upon submitting a file/virus it doesn't report back I don't know why. Although I am using the latest version of CAPE.

**Things to note:**
- Using latest version of CAPE Sandbox
- OS: Ubuntu 22.04
- Guest machine: Windows 10

* When I try to run cape with the following command, I get this error:
**sudo -u cape poetry run python3 cuckoo.py** 

it gives me the following error:
**[root] CRITICAL: CuckooDependencyError: Unable to import libvirt**
![1](https://github.com/kevoreilly/CAPEv2/assets/10081102/de001d7d-e472-49a8-9519-ee3de1b15869)

--------
Instead, I use the following command and it does work:
**python3 cuckoo.py**
![2](https://github.com/kevoreilly/CAPEv2/assets/10081102/2b93fada-227d-4513-a350-6d834a274cb4)

--------

My problem is there is no report generated, I do see the file is being worked on my guest machine (windows 10) and upon completion it doesn't give me any report back but instead this error:
![3](https://github.com/kevoreilly/CAPEv2/assets/10081102/4efd35b7-dc9b-4658-bba9-4a41cc653747)

I've followed the installation guide using github and the following site:
https://capev2.readthedocs.io/_/downloads/en/latest/pdf/

I'm desperately in need of help, I've really tried everything walkthrough so many guides and asked a lot of people.

**Comment by doomedraven** [comment]
hello, check extras/poetry_installer.sh it has example command line how to run it properly to install the dependency. In case the rest of the services is running with poetry. 

About the report itself, did you activate mongodb in `conf/reporting.conf`? is mongo up`sudo systemctl status mongodb`?

**Comment by kevoreilly** [comment]
I feel it's worth asking the question: why are you using an unsupported hypervisor when the installation guides strongly recommend using kvm?

**Comment by doomedraven** [comment]
Since when KVM is unsupported? 😱

**Comment by grimjr90** [comment]
@doomedraven @kevoreilly 

Thanks a lot for your quick response, it really means a lot!

I've firstly done what @doomedraven asked to do, I've checked "extra" folder and found both libvirt_installer.sh and yara_installer.sh, found in file it self how to run them and I've done so.

The commands I ran were:
`cd /opt/CAPEv2/ ; sudo -u cape poetry run extra/libvirt_installer.sh`
`cd /opt/CAPEv2/ ; sudo -u cape poetry run extra/yara_installer.sh`

About report, yes, mongodb is up and status of it showing below:
![r1](https://github.com/kevoreilly/CAPEv2/assets/10081102/6c2e25fd-3bdf-4113-ba1f-fbdb4415494d)
![mongo](https://github.com/kevoreilly/CAPEv2/assets/10081102/9ea6aaac-1043-4bfd-96a3-d911b90b52b1)

Afterwards I tried running `sudo -u cape poetry run python3 cuckoo.py` and it worked and tried submitting another file for analysis and finally I got a report back (Probably the missing part for me was the poetry commands which I mentioned above).
![report](https://github.com/kevoreilly/CAPEv2/assets/10081102/6658e03d-3659-41f8-98b4-ee7b446a4dee)

----------

@kevoreilly I think that I'm using the correct one, isn't it that one mentioned by the guide, it was installed with kvm-qemu.sh
![kvm](https://github.com/kevoreilly/CAPEv2/assets/10081102/664e06c7-fd7c-4e7c-8b92-bc9d5c490309)

**Comment by doomedraven** [comment]
great that you got, it, those scripts are called from cape2.sh and kmv-qemu.sh so i suggest you review the logs to see fi something else is broken. I guess Kev was asking about vmware. so issue can be closed?

**Comment by grimjr90** [comment]
@doomedraven Thanks a lot, for now I'm good! Can I reach you guys for any future issues?

**Comment by doomedraven** [comment]
you are welcome. For sure, is why github has issues ;)  you also can ask here generic questions without opening another issue

**Comment by kevoreilly** [comment]
Yes I was asking about VMware... it says that is the hypervisor in the first line or am I missing something?

**Comment by doomedraven** [comment]
VMware is the core hypervisor, and then vm with KVM aka nested

**Comment by kevoreilly** [comment]
Well it's up to you but to me that's a terrible Idea.

**Comment by grimjr90** [comment]
> Well it's up to you but to me that's a terrible Idea. 

I see, Umm so what would be the your recommendation for running cape?

@doomedraven ive recently been trying it out today, was working fine all long but suddenly started to slow down and website takes long time to launch, what could be the issue?

**Comment by kevoreilly** [comment]
Let me first say that when I first began the CAPE project, I used VMware. I even created the `vmwareserver` and `vmwarerest` machinery modules in CAPE to allow it to run on VMware Workstation 12 and 15, in addition to the existing `vmware` machinery module for ESX.

However, I ran the Windows VMs directly on a single hypervisor. After a few years on VMware someone known as doomedraven introduced me to custom KVM and I realised that a massive slew of anti-virtualisation techniques in malware did not work against KVM like they did against VMware. That was enough for me as the top priority is malware detonation.

But actually here, my first recommendation here isn't against VMware per-se, it's the nested setup. Running a Windows VM nested on two hypervisors can only increase the chances of malware detecting it's running in a vm. To boot you will have massive performance penalty for nesting, and for what? 

There is no technical reason to nest here, CAPE can in theory run in VMware alone with the Ubuntu VM runnning side by side with Windows running directly under VMware too - a single hypervisor.

But since the quality of the results should be the main metric, closely followed by performance, we recommend Ubuntu on bare-metal with KVM only. To me the question is, why wouldn't you just use this setup?

**Comment by doomedraven** [comment]
nested setup if fine when you trying to build that first time and can take snapshots, to revert to previous stage. for best performance is obviously the best to run without any other hypervisor behind, due to double virtualization. 

about slow gui, is probably due to mongodb, idk how much resources you gave to cape server on vmware, so if it doesn't have enough resources everything goes slow. In production my mongo servers takes 300gb of storage and 128gb of ram and that is less than 1w of data. So it all relative and depends of the loads. But as less layers of virtualization you have, more pure resources you can dedicate. 

If you can move mongo to separate VM/host(with proper resources) and point CAPE to it maybe it will help to speedup, but it alos depends of the features that you have enabled, check `web.conf` for existing_results and similar things, i would suggest disable everything that you don't need for optimisations of resources

**Comment by kevoreilly** [comment]
I used snapshots in VMware for the cape server back in the day - yes it is very useful, I may not have been able to succeed without it. But it didn't require nesting.
