### ISSUE TITLE
Relying on a very outdated version of PyMISP

### ISSUE THREAD

**Issue by Rafiot** [kevoreilly/CAPEv2#184]
Someone mentioned an issue related to PyMISP using CAPEv2 and it seems that you're relying on an extremely outdated version of the API: most of the methods you're using have been spitting deprecation warning for over a year by now, and the PyMISP packages released after 2020-01-01 do not support them anymore at all.

I will try to provide a PR (if you're interested), but as I'm not using CAPEv2, I cannot promise the accuracy of the code.

**Comment by doomedraven** [comment]
hello @Rafiot, thanks, ya pymisp in my memory is always broken in cuckoo/cuckoo-modified/cape/capev2, is why i hardcoded a pymisp version, due to deprication of X, so i just stopped to follow and try to keep it up to date, if you can do that would be amazing as it would make a lot of people happy to be able to use latest pymisp, and i have few testers that have capev2 integrated with their misp so they can test it

**Comment by doomedraven** [comment]
i can fix code accuracy, what I just need is the correct pymisp calls to register the data

**Comment by doomedraven** [comment]
thanks again

**Comment by kevoreilly** [comment]
Thank you Rafiot!

**Comment by Rafiot** [comment]
You're welcome, I hope it works fine!
