### ISSUE TITLE
Add_pid_to_aux_modules resolved

### ISSUE THREAD

**Issue by WiltedDeath** [kevoreilly/CAPEv2#1869]
Continuation to this issue: https://github.com/kevoreilly/CAPEv2/issues/1849

So I spent quite a while on looking why add_pid_to_aux didn't get called.....
I added it in this line:
![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/de7f37c3-f726-468b-8c9c-f948058cf4b0)

And it fixed the issue. 

I have one more question regarding this because I am very close in implementing PEsieve as an axuliary module in Cape
I wanted to ask whether I have implemented correctly the storing of the results for pesieve

I copied Usage.py for storing the results in a log file
Here is my code for pe sieve:
![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/e8d676e8-0372-4a1b-b215-f723fd55cda0)

I also get errors connected to result server.py handling the file uploading, is there a limit in Cape about the size of the files uploaded from the Guest?
The errors led me here: https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/resultserver.py#L148C4-L157C19

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/82a03a56-fd62-4403-a1b6-bba56c38c71e)

**Comment by doomedraven** [comment]
as i told you don't need to open new issues to continue. you can stay with closed issue as this is not real cape issue, is user side/code issue.

yes cape has limit on submitted files i think is limited to 100mb, check cuckoo.conf for proper details. your error is because protocol is wrong, you can't use something that you don't know how it works as `NetLogFile`, why just not to use 

```
from lib.common.results import upload_to_host

upload_to_host(self.evtx_dump, "Destinationpath_on_server side")
```

more examples https://github.com/search?q=repo%3Akevoreilly%2FCAPEv2%20upload_to_host&type=code

**Comment by doomedraven** [comment]
also please stay with one uniq issue
