### ISSUE TITLE
Cape strange directory

### ISSUE THREAD

**Issue by WiltedDeath** [kevoreilly/CAPEv2#1881]
Hey , so I m in the final phases of adding a new auxiiliary to Cape for a project of mine.
When I was testing my code, pe sieve dumped the results in  folder I m not familiar with, can someone help?
I cannot find information about it in Cape and its files:

![image](https://github.com/kevoreilly/CAPEv2/assets/119869815/298e08b4-bed8-41d8-98f8-c84490001f4e)
At the end of the code - last 3 lines

**Comment by kevoreilly** [comment]
That is the 'analyzer' directory which you will note contains a copy of the ``analyzer\windows\`` contents including the main Python module ``analyzer.py``. Since it is this module that loads auxiliary modules, this directory is the _current working directory_ and therefore should be accessible programmatically via ``Path.cwd()``.

**Comment by WiltedDeath** [comment]
alright 

so if i understood corectly the analyzer folder gets imported in the windows guest, executes the auxiliaries and they all dump their results in this same folder,
currently pe sieve dumps the results in the current working directory but they dont go back to cape even though i dont see where is the mistake in my code: can you help me out?

[pesieve_integration.txt](https://github.com/kevoreilly/CAPEv2/files/13651839/pesieve_integration.txt)
