### ISSUE TITLE
Introducing CAPE Guru on Gurubase.io

### ISSUE THREAD

**Issue by kursataktas** [kevoreilly/CAPEv2#2344]
Hello CAPE team,

I wanted to update you that I've added the CAPE Guru to Gurubase. Gurubase is a platform that aggregates open-source tools to help developers find information quickly. CAPE Guru uses the data from this repo and the data from [docs](https://capev2.readthedocs.io/en/latest/) to answer questions. I hope you find it useful.

Here is the link to the CAPE Guru: https://gurubase.io/g/cape

I believe CAPE users or new starters would find it useful to have a badge or a link to Gurubase in the README.md. I've prepared two examples below:

Example 1 - Just a badge: 
--
[![](https://img.shields.io/badge/Gurubase-ASK%20CAPE%20GURU-006BFF)](https://gurubase.io/g/cape)

Example 2 - Separate Section:
--
### ✨ Ask CAPE Guru
If you don’t want to get lost in the documentation, you can ask [CAPE Guru](https://gurubase.io/g/cape) directly. It’s an AI that focuses on addressing your questions about CAPE.
[![](https://img.shields.io/badge/Gurubase-ASK%20CAPE%20GURU-006BFF)](https://gurubase.io/g/cape)

If you find it useful, I would be happy to open a PR for this.

Additionally, if you want me to disable CAPE Guru in Gurubase, just let me know that's totally fine.

**Comment by doomedraven** [comment]
hello, it looks fine, about the badge, im not sure, i will leave that part to decide to the owner @kevoreilly. As docs pointed in first line of readme. Asking parts is nice, but if users doesn't read whole docs, when they setup first time, they won't be successful in proper usage of the tool

**Comment by kursataktas** [comment]
Thanks for the review @doomedraven 

> Asking parts is nice, but if users doesn't read whole docs, when they setup first time, they won't be successful in proper usage of the tool
As most of the answers point users to relevant parts of the documentation, they’ll have the opportunity to explore the full page if they need more detailed information. This way, they can learn at their own pace while still having access to the necessary guidance.

Hi @kevoreilly, I’ve created a [PR](https://github.com/kevoreilly/CAPEv2/pull/2355) for this. I’d love to hear your thoughts on the contribution whenever you have a chance.

**Comment by kevoreilly** [comment]
Hi Kürşat, thank you for this PR. As doomed has said the documentation needs to be understood before installation is started as there are many pitfalls which would require starting from scratch if fallen into - vm creation is just one example.

Also we have put a lot of effort into the documentation and support channels which I don't think would be helped with this addition.

Finally we will soon be launching a github.io site with some more detailed posts about advanced cape usage.

I hope you will understand that we would like to focus on getting these things right rather than adding to the list with something else. For that reason I would be grateful if you would disable the guru for cape.

Thanks for the suggestion nonetheless, and kind regards!

**Comment by kursataktas** [comment]
Thank you for your consideration. I removed the CAPE Guru as you requested.
