### ISSUE TITLE
Cape failed processing

### ISSUE THREAD

**Issue by Solumnant** [kevoreilly/CAPEv2#239]
# Expected Behavior

cape succeeds processing files

# Current Behavior

cape failed processing on excell spreadsheet

# Failure Information (for bugs)

https://capesandbox.com/submit/status/39885/

**Comment by kevoreilly** [comment]
Can you try submitting for less time? It's probably just timing out due to excessive behavior logs which is a perennial problem on the public instance. The answer is to submit with less time as we cannot increase the processing timeout any more - this just leads to the sandbox dying as it allows ludicrously sized behavior logs to get processed which just kills it for everyone.

**Comment by Solumnant** [comment]
I thought I submitted it with the standard time out of 200, what would be
appropriate for the public instance?

**Comment by kevoreilly** [comment]
Hmm it looks like it might be a different problem here - I'm reprocessing now in debug mode to see what's going wrong.

**Comment by kevoreilly** [comment]
I'm not sure if that was the problem or not - I reprocessed the new job with timeout 100 and it worked.

The bigger question is a bit more tricky. There is basically no such thing as a perfect timeout - the current default of 200 is way too big for some samples, only just enough for others, I think the big problem is that people don't equate a failure in processing to a job that generated too much output to process in the timeout. This should be a prompt to try a lesser timeout. I almost never submit with the default timeout unless I know the malware needs it. If it doesn't detonate in, say, 60 secs I am happy to resubmit with 120 etc, rather than just accepting the default. To submit a ransomware sample for 200 seconds is just asking for trouble. It's like revving your car engine at the red line for 5 minutes just because it should be able to handle it.
