### ISSUE TITLE
Strange rendering when using Guac web

### ISSUE THREAD

**Issue by seanthegeek** [kevoreilly/CAPEv2#2432]
The "interactive session" feature of CAPE isn't very usable due to strange rendering. Here are screenshots of example.com in Chrome on a sandbox VM.

Microsoft Windows client with an AMD GPU.

## Microsoft Edge

![image](https://github.com/user-attachments/assets/15b4126f-fabe-4a4e-bf45-84a7ac563dcd)

## Firefox

![image](https://github.com/user-attachments/assets/c715e6f8-697d-480a-8ce8-b4f4df06c5b4)

**Comment by ChrisThibodeaux** [comment]
Does this only happen when using Guac or do you see the same behavior when the desktop view is launched from virt-manager? I had a very similar issue, but it was not limited to the display via Guac.

I'm assuming you changed your changed your display type to `VNC Server`? If so, the issue may be that the video model is still set to the SPICE model, `QXL`.For me, the fix was just changing the video model. First tried using `VGA` with decent results, but limited higher resolution options and I found virtualization artifacts within the VM from using it. Editing the vm's xml directly and using `vmvga` gave me the best results.

Side note, `vmvga` is apparently the VMWare video model. Loaded fine for me with KVM/QEMU without installing any additional drivers.

Relevant parts of the xml:
```
...
    <graphics type="vnc" port="-1" autoport="yes" listen="127.0.0.1">
      <listen type="address" address="127.0.0.1"/>
    </graphics>
...
    <video>
      <model type="vmvga" vram="16384" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
    </video>
...
```

**Comment by seanthegeek** [comment]
Ah, yeah. When creating VMs in `virt-manager` they start out with a `qxl` video adaptor and a `spice` video display. I added a second `display` with type `vnc` instead of changing the existing `spice` display to `vnc`. I did't notice the issues with VNC until using CAPE's "interactive session"/guac-web` because `virt-manager` preferred to connect to the SPICE display.

Changing the video adaptor `type` from `qxl` to `vmvga` and removing the `ram` and `vganem` attributes that VMVGA does not use fixed it. Thanks!

Before:

```xml
<video>
  <model type="qxl" ram="65536" vram="65536" vgamem="16384" heads="1" primary="yes"/>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
</video>
```

After

```xml
<video>
  <model type="vmvga" vram="65536" heads="1" primary="yes"/>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
</video>
```
