### ISSUE TITLE
VirusTotal and the NSIS Integrity Check function

### ISSUE THREAD

**Issue by bLightZP** [kevoreilly/CAPEv2#2444]
I tried searching the web and even consulting with AI and couldn't find an answer to this.

VirusTotal is using CAPEv2 to scan EXE files.
I submitted an [installer I created myself](https://www.virustotal.com/gui/file/829935a6a2bed88deae0adc4ba9a4895d3a0ce977da93c245a17435835e5c792) using NSIS and then digitally signed the resulting EXE with a code signing certificate.

VirusTotal is reporting that CAPEv2's "NSIS Integrity Check function" (see below) is being triggered.

I am trying to figure out why this rule is triggered, could it possibly be the code signing certificate? And if it is, is there a way to work around this issue? It doesn't make sense for VirusTotal to report every signed NSIS EXE as suffering from an integrity check issue.

Here's a direct link to the installer EXE:
https://www.zptechnology.com/download/zp2000max.exe

P.S.
I directly contacted VirusTotal on this issue, but it would really help to have your insight.

```
rule NSIS
{
    meta:
        author = "kevoreilly"
        description = "NSIS Integrity Check function"
        cape_options = "exclude-apis=LdrLoadDll"
        hash = "d0c1e946f02503a290d24637b5c522145f58372a9ded9e647d24cd904552d235"
    strings:
        $check = {6A 1C 8D 45 [3-8] E8 [4] 8B 45 ?? A9 F0 FF FF FF 75 ?? 81 7D ?? EF BE AD DE 75 ?? 81 7D ?? 49 6E 73 74 75 ?? 81 7D ?? 73 6F 66 74 75 ?? 81 7D ?? 4E 75 6C 6C 75 ?? 09 45 08 8B 45 08 8B 0D [4] 83 E0 02 09 05 [4] 8B 45 ?? 3B C6 89 0D [4] 0F 8? [2] 00 00 F6 45 08 08 75 06 F6 45 08 04 75}
    condition:
        uint16(0) == 0x5A4D and all of them
}
```

**Comment by kevoreilly** [comment]
This feels like deja vu... but this is definitely the place to get the answer, although is it the right question? I don't think so.

The reason it's detected it because that is the singular unique goal of the yara signature. Why is that a problem? Probably because somewhere this is being misinterpreted as some sort of judgment as to whether it's malicious or not. But that isn't cape's problem! As far as this sandbox is concerned, there is a technical reason (detonation success) that depends upon it. That is it, all and everything. It doesn't mean it's malicious, nor benign. It's literally like a mechanical cog in a machine where its absence would mean a failure of detonation for any nsis executable, no more, no less.

**Comment by bLightZP** [comment]
From what I understand from your response, you believe that VirusTotal is mishandling the result of this rule or not making it clear enough that the result is not indicative of a safety warning, especially if the file is signed with a coding certificate.

Any chance you have contacts in VirusTotal that can be persuaded to change the way in which the results of this rule are presented?

**Comment by kevoreilly** [comment]
It's difficult to respond precisely to vague terms like 'mishandling' - I can't comment on the VirusTotal side too much other than to say that this signature is not an indicator of maliciousness or otherwise.

I know a few contributors with contacts at VT - I will try raise the inclusion of the moinitor yara signatures to see if this is really what is intended since this is a distinct collection of yara signatures that exists for ingestion by the sandbox only. They are not intended for classification or a verdict of maliciousness.

**Comment by kevoreilly** [comment]
P.S. unfortunately the presence of a valid digital signature makes no difference here - this signature checks for the presence of very specific code bytes which are unique to NSIS and which appear in all NSIS exes:

![image](https://github.com/user-attachments/assets/6fe54a8f-8774-4c44-b832-b9c234b3f184)

It's like a code fingerprint. The reason this signature is needed in CAPE is that without it, NSIS archives fail to detonate due to the presence of an API hook on the ntdll function ``LdrLoadDll``. The hook and NSIS do not get on and so it's necessary to disable the hook to allow NSIS archives to run in the sandbox.
