### ISSUE TITLE
Allow the ability to restart the VM when persistence is detected. [Possible Feature]

### ISSUE THREAD

**Issue by powerade661** [kevoreilly/CAPEv2#269]
## This is opensource and you getting __free__ support so be friendly!

**Background**

Malware will often times write itself to the registry and not make a call-out to the c2 server until the system is rebooted. It would be nice to be able to reboot the VM and still have analysis performed again when the system is back up.

**Comment by doomedraven** [comment]
You can backport that from upstream cuckoo and make pull request with that

**Comment by kevoreilly** [comment]
I have never looked at Cuckoo's solution to this but the problem is in monitoring the process(es) after reboot. The way monitoring works currently is to inject the monitor into the original process, and then catch any child processes/injections via api hooks and ensure the monitor is injected into these processes before these apis complete. How we would do this with a process started by any number of autostart mechanism on reboot is a mystery to me... 

...but it sounds like a lot of work one way or another. As doomed said: happy to accept pull requests but otherwise this feature idea will have to remain just that I'm afraid.

**Comment by capeuser21** [comment]
i am also seeking to use/implement a similar feature and would like to know whether there is any progress made towards this possible feature? otherwise, is it possible to provide certain tips on how to implement such a feature?

**Comment by kevoreilly** [comment]
The problem is described above. Monitoring works by injecting the monitor into all malware processes. How to catch them automatically at reboot?

I know the scope of potential persistence mechanisms is vast, many probably lie unknown currently. To have a way of picking out the bad processes at boot sounds like the pot of gold at the end of the rainbow.
