### ISSUE TITLE
Emotet is no longer detected after updating

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#361]
## This is open source and friendly with __free __ support!

Thank you for always answering the questions!

# Prerequisites

Please answer the following questions yourself before submitting your question.

-[x] Running the latest version
-[x] I checked the docs but couldn't find the answer
-[x] Confirmed that this issue has not yet been submitted
-[x] Report problem to correct repository (for multi-repository project)

# Expected behavior

Emotet can be detected by yara and confirmed in the report.

# Current behavior

I have an Emotet yara rule in my cape (which is included by default), but when I analyze the Emotet exe file, the report doesn't detect it as Emotet.

This happened when I updated the Cape to the latest version.
The cape before the update was able to detect Emotet, so something may have changed with the update ... I'm sorry, I don't know.

The following files were modified by the update.

```
-rw-r--r-- 1 cape cape 1334 July 31 07:55 MassLogger.yar
-rw-r--r-- 1 cape cape 3118 September 9 12:11 auxiliary.conf
-rw-r--r-- 1 cape cape 6282 September 9 11:54 cuckoo.conf
-rw-r--r-- 1 cape cape 14127 August 20 01:29 guest.py
-rw-r--r-- 1 cape cape 5680 July 31 07:55 physical.py
```

Also, I tried to check if the latest cape can be detected at https://www.capesandbox.com, but I could not do it with Error 524

# Procedure to reproduce

Please provide detailed steps to reproduce the problem.

1. Upload Emotet to cape.
2. After the Emotet analysis is complete, check the report.
3. Emotet has not been detected.

# Environment

Machine use VirtualBox
Host machine: ubuntu 20.04.1 LTS
Guest machine: Windows 10 (python3.8 installed and environment variables set)

# Failure log
None

**Comment by kevoreilly** [comment]
The first thing to look at with issues such as this is the chain of requirements that leads to detection and config extraction. These are:

Detonation -> payload extraction -> detection by YARA -> config parsing

So the obvious first question is: is the sample detonating properly? Are payloads extracted (i.e. files in the cape or procdump tabs)?

If so then the next step is to download those payloads, and scan them manually with the Emotet YARA sig. If they are not detected then your problem is more one of detonation & payload extraction inside the VM. If they are detected, then something has gone wrong with the post-processing with the YARA scans.

Let me know!

**Comment by kevoreilly** [comment]
Also if you do a git log --oneline  you will see where the updates are, you could always quickly checkout an older commit and see if that makes everything work again.

**Comment by kevoreilly** [comment]
All working in cape so closing

**Comment by ai-suzuki** [comment]
I'm sorry, my reply was late.
I decided to use a snapshot when it worked.
I will update it someday and try it.
