### ISSUE TITLE
When object is not found, HTTP status code should be 404

### ISSUE THREAD

**Issue by CrimsonGlory** [kevoreilly/CAPEv2#374]
Minor report. When object is not found, HTTP status code should be 404, not 200.

Example:
https://github.com/kevoreilly/CAPEv2/blob/140d1bfc2905231704f6cc8cfe4f7f2efc61cd8d/web/api/views.py#L1393

```
* Connected to 192.168.1.23 (192.168.1.23) port 4545 (#0)
> GET /api/tasks/get/screenshot/1138/6/ HTTP/1.1
> Host: 192.168.1.23:4545
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 03 Dec 2020 19:24:47 GMT
< Content-Type: application/json; charset=UTF-8
< Server: Machete Server
< X-Cuckoo-Version: 2.1-CAPE
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< Cache-Control: no-cache
< Expires: 0
< Content-Length: 69
< 
{
    "error": true,
    "error_value": "Screenshot does not exist"
}
```

**Comment by doomedraven** [comment]
well yes and no. the problem is that was designed a lot of time ago and would require to update all the fields, that we not interested as we have more important things ToDo.

200 means page found, but you have error fields especially for that, as then if you would do typo in url, you will get 404 too, so that would complicate for some users, if you would like to introduce status for that cases, you are welcome to push pull request, we are open for collaboration
