### ISSUE TITLE
Sandbox Evasion

### ISSUE THREAD

**Issue by basilhskk** [kevoreilly/CAPEv2#423]
Since we could not find any e-mail to report about the online cape version, we have noticed the following that may allow malware to evade several tests:

- Small amount of threads (2) for a modern CPU.

- Consider running pafish in your VMS as the VM can be detected by the CPU timestamp counters (rdtsc).

- It would be wise to leave an application in the foreground to show that someone opened the app.

**Comment by doomedraven** [comment]
thanks. 

2. we more then aware about everything, and our personal suggestion instead of pafish use https://github.com/LordNoteworthy/al-khaser
3. that can be done by packages, for example Ostap malware does check of running processes and user can handle that, in case if would be needed we can start them easilly

**Comment by kevoreilly** [comment]
@basilhskk I thought you might be interested to know that Pafish sandbox evasion is now successfully bypassed with this YARA sig:

rule Pafish
{
    meta:
        author = "kevoreilly"
        description = "Pafish bypass"
        cape_options = "bp0=$rdtsc_vmexit-2,action0=skip,bp1=$rdtsc_vmexit-2,action1=skip,count=1"
    strings:
        $rdtsc_vmexit = {8B 45 E8 80 F4 00 89 C3 8B 45 EC 80 F4 00 89 C6 89 F0 09 D8 85 C0 75 07}
    condition:
        uint16(0) == 0x5A4D and $rdtsc_vmexit
}
 
See for example:
https://www.capesandbox.com/analysis/116309
