### ISSUE TITLE
Memory dump on Proxmox not found

### ISSUE THREAD

**Issue by vinceplayer** [kevoreilly/CAPEv2#468]
# Expected Behavior

When I enable the memory dump to integrate malconfscan functionality into an environment with proxmox, I notice that the memory dump does not work (memory dump not found), and the machinery/proxmox source code I do not see the function for the dump. Am I doing something wrong?

# Current Behavior

No memory dump generate

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable proxmox machinery
2. enable memory dump
3. execute malware
4. VM memory dump not found

| Question         | Answer
|------------------|--------------------
| Git commit       | last version
| OS version       | Ubuntu 19.94, Windows 7, macOS 10.12.3

**Comment by kevoreilly** [comment]
Yes the real error here is to try and integrate malconfscan into cape instead of integrating the parsers from malconfscan into cape within the existing framework and relying on payload capture and process dumps for unpacked samples.

Which families are you after? I will integrate them myself on principle.

**Comment by kevoreilly** [comment]
Also which sandbox are you using?

**Comment by vinceplayer** [comment]
Sandbox is cape, the problem is dump of memory with proxmox. With virtualbox i have no problem of dump, emotet is recognized, but with proxmox with machinery moduled no dump is generated.

Missing the function dump_memory in proxmox.py

**Comment by kevoreilly** [comment]
I understand what you are stating the problem is - however as I have stated integrating malconfscan with cape is absolute folly.

So tell me - why are you determined to try and integrate malconfscan with cape and use full system memory dumps with volatility? Why are you essentially ignoring the whole framework that exists within cape to capture payloads, detect them via yara signatures and trigger parsers using one of a choice of config parsing frameworks? What did I spend six years of my life developing all that stuff for?!

**Comment by vinceplayer** [comment]
I apologize I misunderstood the use of cape, it was not my intention to offend.

CAPE therefore does not act on the memory dump to understand the type of malware?

**Comment by kevoreilly** [comment]
Yes but rather than relying on crude full system memory dumps which are then interpreted by volatility to parse out the interesting info, the principle in cape is to dump this stuff from within the process as it's running. Thus the output in cape at the end of the job should comprise process dumps and 'payloads' which are other memory dumps taken dynamically when other payloads (shellcode or PE images) are detected during detonation.

All this dumping is done by the monitor which is injected into every process that is tracked by cape. The monitor even includes a debugger so you can even breakpoint on an exact instruction in your malware to dump at the perfect moment (say for a working unpacked sample) so it is a lot more refined and powerful a tool than looking at some memory dump after it's all over.

This is why I asked which malware families you are interested in from malconf scan, as I would hope and expect that cape can already capture the unpacked malware payloads, and that all that is required to add config extraction for this family would be to add an appropriate yara signature and to add the parser from malconfscan, albeit with some potential small modifications,

**Comment by vinceplayer** [comment]
I apologize I misunderstood the use of cape, it was not my intention to offend.

CAPE therefore does not act on the memory dump to understand the type of malware?

**Comment by vinceplayer** [comment]
I understand thanks for the thousand tips.
I close the topic
