### ISSUE TITLE
Offer to Host a VM

### ISSUE THREAD

**Issue by iguy0** [kevoreilly/CAPEv2#474]
Hello there,

Just an idea really. I would like to volunteer by hosting a preconfigured VM via torrent or similar. 
This would streamline and standardize even further the project's adoption and recognition.

Awesome job by the way, I'm a fan myself.

Happy Easter!

**Comment by doomedraven** [comment]
Hello, Kevin wanted to do that few times, but meh,
* no time
* nobody will keep that up to date(3rd pard software + cape software)

you have 2 scripts pointed in readme, that does that pretty quickly the deploy to latest

enjoy the holidays

**Comment by kevoreilly** [comment]
Hi iguy0 - I do think this could be a good idea - anything that could help with adoption or recognition would be very welcome. 

I presume you mean have a Ubuntu vm with cape installed to run alongside the Windows vms, controlling the hypervisor 'remotely' via virtual network and kvmremote machinery? This could work nicely, but it still leaves the thorny issue of the Windows vms which we can't really pre-package due to licensing. 

It could be argued that the tricky part of setting it all up is in the connectivity between vms and server so that even with a cape vm, it would still not be trivial to deploy. But then again, every little helps. I think the thing that would prove the most onerous would be, as doomed says, keeping the vm up-to-date continuously and hosting it - if that is something you think you could handle then maybe we could give it a go...

**Comment by doomedraven** [comment]
Kevin don't forget that "work nicelly and remotelly" would require users to learn set firewall as if no rooter would be 100% useless and all traffic would be directly leaked so you just overcomplicate that

**Comment by kevoreilly** [comment]
Ah yes this is a good point that I hadn't thought of....

**Comment by iguy0** [comment]
I was thinking along the lines of having a vm with almost everything already configured. 

Some vagrant scripts(https://codeblog.dotsandbrackets.com/vagrant-windows/) available for use to build the windows VM. The release schedule could be twice a year, with the user in charge of updating the OS. When releasing, use the latest available version + current working ubuntu.

1- Who would create the VM? (I could i guess.. but if you guys could provide would be best)
2- I could host a spot or torrent or both.. =]

We could also have a windows 10 VM(without disk) already created within the VM, with every hack we can pack. (i think this part could also be a selling point) 

I believe some of CAPE's users(or not yet..) would be interested in something like this. I think a lot of the people out there download and try new tools and toys but at the end they stick with what's easy. It's easy enough to drive usage and adoption by people teaching classes, building small labs, the 14 year old in the basement learning stuff for the first time lol, you get the point.

**Comment by doomedraven** [comment]
The problem of vargrant is that it uses vbox as fae as i remember and we
dont recommend to use that at all, if ypu want a good enviroment, use kvm

**Comment by kevoreilly** [comment]
Yeah there are a couple of issues with what you suggested - doomed is right, there is no virtualbox with cape. No vmware, no nothing except kvm - consider how much work has gone into stuff like anti-evasion, this is all sacrificed with a rubbish easily detectable hypervisor like vbox.

Secondly and perhaps more importantly it sounds like you are describing nesting virtualisation. Running a windows vm inside a linux vm? This is a huuuge no no - massive performance hit for no good reason and a big question mark over vm detectability.

**Comment by iguy0** [comment]
Ok. Let's scrap the vagrant idea. It was bad.. I can think of another suitable solution to automate(or close to it) the windows deployment portion. 

By going the nested virtualization route, the user would take a hit on performance, but at least it would help "spreading the word" about CAPE and what it can do, by having a extremely easy to deploy dynamic analysis solution.

**Comment by doomedraven** [comment]
>  "spreading the word"
exactly what Kevin told, about the antivms that we work so hard will be useless and many other things, so that most will show "how bad cape is" not how great.

i understand that having nested thing is nice to quick tests/playing/get familiar, but giving that to users with bad performance, problems with antivm defeating, we won't spend time on giving that to user and spend our free time on that

**Comment by doomedraven** [comment]
for extreamely easy solution you have capesandbox.com and you can set TLP flag ;)
