### ISSUE TITLE
CAPEv2 generates an exception during execution Amadey packed using Obsidium

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/CAPEv2#748]
Binary sha256: 93bbc7e0f489125883985855949ed8a0929d44b5fea0c17db9113fff830793c9

Exception:

![amadey](https://user-images.githubusercontent.com/55275842/152525175-aa16d86f-4bca-42dd-8b33-1e52d17e43fb.jpg)

**Comment by kevoreilly** [comment]
Thank you for reporting this issue. Initial triage suggested this is a hook issue, and a hook sweep has located the breaking hook as CreateProcessInternalW - it is of note that the sample detonates correctly with exclude-apis=CreateProcessInternalW

The next phase of work is to identify why this hook is causing this issue and to hopefully resolve the issue whilst leaving this important hook working properly - watch this space.

**Comment by kevoreilly** [comment]
The rabbit hole lead down into the loader where a bug in checking if a process has already been IAT patched (injected) was causing this check to fail. It's fixed in https://github.com/kevoreilly/CAPEv2/commit/7d4979589e41cf4a4c92860cea559f946bb163de

Thanks again for reporting this issue and helping to make CAPE better.
