### ISSUE TITLE
[Feature Request] User Submissions Link

### ISSUE THREAD

**Issue by klikevil** [kevoreilly/CAPEv2#842]
Hi this is a feature request, I'd like a list of all my submissions from my user (or other people's users for that matter) to be viewable within my profile to track them more easily.  A lot of my jobs haven't been completing successfully even with enforce timeout.

https://capesandbox.com/submit/status/268731/ for instance

**Comment by doomedraven** [comment]
hello, the issue with your task is that you set machine, as main server db was set long time ago we need to do some update to make it working, just not set machine name should solve your issue

about feature request, maybe in future, as allow to user list their tasks is ok, but of other people tasks idk if that is ok

**Comment by klikevil** [comment]
> hello, the issue with your task is that you set machine, as main server db was set long time ago we need to do some update to make it working, just not set machine name should solve your issue
> 
> about feature request, maybe in future, as allow to user list their tasks is ok, but of other people tasks idk if that is ok

That's absolutely fine!  I mainly just need to track my own submissions anyway 👍 

Thanks for the tip on the machine name.

**Comment by doomedraven** [comment]
hello now you can search all your jobs, well not all, but only view last 50(limit on public) on personal can be changed

to use it on capesandbox.com you need to do login and then put in search: `user_tasks:givemethemall` the <givemethemall> doesn't matter due to it uses user id from mongo to not leak others users jobs, but value should be more 3 or more chars/digits after user_tasks ;)
