### ISSUE TITLE
Signature Attribute Clarification

### ISSUE THREAD

**Issue by cccs-kevin** [kevoreilly/CAPEv2#897]
Can someone please explain to me what `weight`, `confidence`, and `severity` mean and how they are to be interpreted for a `Signature`?

https://github.com/kevoreilly/CAPEv2/blob/6de60f504e87fd8a59a182a3f3cdad8b604adddd/lib/cuckoo/common/abstracts.py#L719:L721

Is seems like the only place they are used is here, for calculating the total score:

https://github.com/kevoreilly/CAPEv2/blob/5b3ceea578e0d90cbd61886b443a37cb13160c64/lib/cuckoo/core/plugins.py#L585:L588

From what I understand, `confidence` is how confident the signature writer is that the signature is not a false positive, `severity`'s definition is [here](https://github.com/kevoreilly/CAPEv2/blob/master/docs/book/src/customization/signatures.rst#L116), but where does `weight` fit into all of this?

I'll add the answer to the documentation to assist others in the future.

**Comment by kevoreilly** [comment]
It sounds like weight is just a way to fudge the scores - malscore is inherited from Cuckoo and is not something I ever rated. I left it in only because some still apparently use/like it, but left it disabled by default in CAPE as it has a far superior classification method than Cuckoo had (Yara scans of extracted payloads). Maybe this should be reflected in the documentation.
